### PR TITLE
Update Orcs.json

### PR DESCRIPTION
**Pull request by Xpyder**
json fix

missing some commas
Also corrected a couple white space typos.

note, you can also check for problems using a [JSON Linter](https://jsonformatter.curiousconcept.com/)

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
thanks, I'll see if it works, btw, how do I test these features?

**Comment by Xpyder** [comment]
Like in the game?

if it's just json changes you could overwrite a copy of the game (maybe use the launcher so any changes are easy to overwrite with current base)

if it includes cpp changes you'd need to have a compiler.  There's a section on the github on how to do that but I haven't reviewed it myself yet.

And just an FYI: you may know this but adding this by itself won't make them spawn.  They need to be added to either map tiles or spawn groups elsewhere (I haven't traced that part out before so I don't know exactly where that would be)

**Comment by Xpyder** [comment]
Although for basic testing you could try overwriting one of the existing monsters like a goblin, stealing it's id and flags to get the game to include it

**Comment by Theawesomeboophis** [comment]
Thanks, I'll try and set them to spawn somewhere.

**Comment by Theawesomeboophis** [comment]
I'm gonna set them to spawn in cities, as Orcs usually live in groups or tribes, an alternative to this could be to rework Goblin camps to spawn orcs, and then make the orc camps a separate building somehow.

**Pull request merged**
